//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scrubbler.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Username {
            get {
                return ((string)(this["Username"]));
            }
            set {
                this["Username"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ITunesAutoConnect {
            get {
                return ((bool)(this["ITunesAutoConnect"]));
            }
            set {
                this["ITunesAutoConnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ArtistFieldIndex {
            get {
                return ((int)(this["ArtistFieldIndex"]));
            }
            set {
                this["ArtistFieldIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int AlbumFieldIndex {
            get {
                return ((int)(this["AlbumFieldIndex"]));
            }
            set {
                this["AlbumFieldIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int TrackFieldIndex {
            get {
                return ((int)(this["TrackFieldIndex"]));
            }
            set {
                this["TrackFieldIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int TimestampFieldIndex {
            get {
                return ((int)(this["TimestampFieldIndex"]));
            }
            set {
                this["TimestampFieldIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int AlbumArtistFieldIndex {
            get {
                return ((int)(this["AlbumArtistFieldIndex"]));
            }
            set {
                this["AlbumArtistFieldIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int DurationFieldIndex {
            get {
                return ((int)(this["DurationFieldIndex"]));
            }
            set {
                this["DurationFieldIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SpotifyAutoConnect {
            get {
                return ((bool)(this["SpotifyAutoConnect"]));
            }
            set {
                this["SpotifyAutoConnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoScrobbleCache {
            get {
                return ((bool)(this["AutoScrobbleCache"]));
            }
            set {
                this["AutoScrobbleCache"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",")]
        public string CSVDelimiters {
            get {
                return ((string)(this["CSVDelimiters"]));
            }
            set {
                this["CSVDelimiters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MinimizeToTray {
            get {
                return ((bool)(this["MinimizeToTray"]));
            }
            set {
                this["MinimizeToTray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartMinimized {
            get {
                return ((bool)(this["StartMinimized"]));
            }
            set {
                this["StartMinimized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool StartupUpdateCheck {
            get {
                return ((bool)(this["StartupUpdateCheck"]));
            }
            set {
                this["StartupUpdateCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CSVEncoding {
            get {
                return ((int)(this["CSVEncoding"]));
            }
            set {
                this["CSVEncoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CSVHasFieldsInQuotes {
            get {
                return ((bool)(this["CSVHasFieldsInQuotes"]));
            }
            set {
                this["CSVHasFieldsInQuotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseRichPresenceITunes {
            get {
                return ((bool)(this["UseRichPresenceITunes"]));
            }
            set {
                this["UseRichPresenceITunes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("master_metadata_track_name")]
        public string JSONTrackNameProperty {
            get {
                return ((string)(this["JSONTrackNameProperty"]));
            }
            set {
                this["JSONTrackNameProperty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("master_metadata_album_artist_name")]
        public string JSONArtistNameProperty {
            get {
                return ((string)(this["JSONArtistNameProperty"]));
            }
            set {
                this["JSONArtistNameProperty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("master_metadata_album_album_name")]
        public string JSONAlbumNameProperty {
            get {
                return ((string)(this["JSONAlbumNameProperty"]));
            }
            set {
                this["JSONAlbumNameProperty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("albumArtist")]
        public string JSONAlbumArtistNameProperty {
            get {
                return ((string)(this["JSONAlbumArtistNameProperty"]));
            }
            set {
                this["JSONAlbumArtistNameProperty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ts")]
        public string JSONTimestampProperty {
            get {
                return ((string)(this["JSONTimestampProperty"]));
            }
            set {
                this["JSONTimestampProperty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("duration")]
        public string JSONDurationProperty {
            get {
                return ((string)(this["JSONDurationProperty"]));
            }
            set {
                this["JSONDurationProperty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstStart {
            get {
                return ((bool)(this["FirstStart"]));
            }
            set {
                this["FirstStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ms_played")]
        public string JSONMillisecondsPlayedProperty {
            get {
                return ((string)(this["JSONMillisecondsPlayedProperty"]));
            }
            set {
                this["JSONMillisecondsPlayedProperty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool JSONFilterShortPlayedSongs {
            get {
                return ((bool)(this["JSONFilterShortPlayedSongs"]));
            }
            set {
                this["JSONFilterShortPlayedSongs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int JSONPlayedMillisecondsThreshold {
            get {
                return ((int)(this["JSONPlayedMillisecondsThreshold"]));
            }
            set {
                this["JSONPlayedMillisecondsThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int CSVMillisecondsPlayedFieldIndex {
            get {
                return ((int)(this["CSVMillisecondsPlayedFieldIndex"]));
            }
            set {
                this["CSVMillisecondsPlayedFieldIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CSVFilterShortPlayedSongs {
            get {
                return ((bool)(this["CSVFilterShortPlayedSongs"]));
            }
            set {
                this["CSVFilterShortPlayedSongs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int CSVPlayedMillisecondsThreshold {
            get {
                return ((int)(this["CSVPlayedMillisecondsThreshold"]));
            }
            set {
                this["CSVPlayedMillisecondsThreshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoConnectAppleMusic {
            get {
                return ((bool)(this["AutoConnectAppleMusic"]));
            }
            set {
                this["AutoConnectAppleMusic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseRichPresenceAppleMusic {
            get {
                return ((bool)(this["UseRichPresenceAppleMusic"]));
            }
            set {
                this["UseRichPresenceAppleMusic"] = value;
            }
        }
    }
}
